import { Candidate } from "@/types";

export const DUMMY_CANDIDATES: Omit<Candidate, "_id">[] = [
  {
    firstName: "Alice",
    lastName: "Nkurunziza",
    email: "alice.nkurunziza@example.com",
    headline: "Senior Backend Engineer – Node.js & AI Systems",
    bio: "Passionate backend engineer with 7 years building scalable APIs and integrating AI/ML models into production systems. Open-source contributor and technical mentor.",
    location: "Kigali, Rwanda",
    skills: [
      { name: "Node.js", level: "Expert", yearsOfExperience: 7 },
      { name: "TypeScript", level: "Expert", yearsOfExperience: 5 },
      { name: "MongoDB", level: "Advanced", yearsOfExperience: 5 },
      { name: "PostgreSQL", level: "Advanced", yearsOfExperience: 4 },
      { name: "Gemini API", level: "Advanced", yearsOfExperience: 2 },
      { name: "Docker", level: "Advanced", yearsOfExperience: 4 },
      { name: "Redis", level: "Intermediate", yearsOfExperience: 3 },
      { name: "GraphQL", level: "Intermediate", yearsOfExperience: 2 },
    ],
    languages: [
      { name: "English", proficiency: "Fluent" },
      { name: "Kinyarwanda", proficiency: "Native" },
      { name: "French", proficiency: "Conversational" },
    ],
    experience: [
      {
        company: "Andela",
        role: "Senior Backend Engineer",
        startDate: "2021-03",
        endDate: "Present",
        description: "Led backend architecture for a talent marketplace platform serving 50,000+ developers. Designed microservices architecture using Node.js and TypeScript. Integrated AI screening tools using Google Gemini API.",
        technologies: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "Docker", "Kubernetes"],
        isCurrent: true,
      },
      {
        company: "Kora",
        role: "Backend Engineer",
        startDate: "2018-06",
        endDate: "2021-02",
        description: "Built payment processing APIs handling $2M+ daily transactions. Implemented fraud detection using ML models.",
        technologies: ["Node.js", "MongoDB", "RabbitMQ", "AWS Lambda"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "Carnegie Mellon University Africa",
        degree: "Master's",
        fieldOfStudy: "Information Technology",
        startYear: 2016,
        endYear: 2018,
      },
    ],
    certifications: [
      { name: "AWS Certified Solutions Architect", issuer: "Amazon", issueDate: "2022-05" },
      { name: "Google Cloud Professional Developer", issuer: "Google", issueDate: "2023-02" },
    ],
    projects: [
      {
        name: "TalentMatch AI",
        description: "AI-powered recruitment platform using Gemini API to match candidates to roles with 90% accuracy.",
        technologies: ["Node.js", "TypeScript", "Gemini API", "MongoDB", "Next.js"],
        role: "Lead Backend Engineer",
        link: "https://github.com/alice-nk/talent-match",
        startDate: "2023-06",
        endDate: "2023-12",
      },
      {
        name: "Open Payment SDK",
        description: "Open-source payment SDK for African fintechs supporting Mobile Money, VISA, and Mastercard.",
        technologies: ["Node.js", "TypeScript", "Jest"],
        role: "Creator & Maintainer",
        startDate: "2021-01",
        endDate: "2023-01",
      },
    ],
    availability: { status: "Available", type: "Full-time", startDate: "2026-05-01" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/alice-nk",
      github: "https://github.com/alice-nk",
    },
    source: "platform",
  },
  {
    firstName: "Brian",
    lastName: "Odhiambo",
    email: "brian.odhiambo@example.com",
    headline: "Full-Stack Engineer – React & Node.js | 5 Years",
    bio: "Full-stack engineer specializing in React/Next.js frontends and Node.js backends. Built products used by 100,000+ users across East Africa.",
    location: "Nairobi, Kenya",
    skills: [
      { name: "React", level: "Expert", yearsOfExperience: 5 },
      { name: "Next.js", level: "Advanced", yearsOfExperience: 4 },
      { name: "Node.js", level: "Advanced", yearsOfExperience: 4 },
      { name: "TypeScript", level: "Advanced", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Intermediate", yearsOfExperience: 3 },
      { name: "Tailwind CSS", level: "Expert", yearsOfExperience: 3 },
      { name: "Redux", level: "Advanced", yearsOfExperience: 4 },
      { name: "REST APIs", level: "Advanced", yearsOfExperience: 5 },
    ],
    languages: [
      { name: "English", proficiency: "Fluent" },
      { name: "Swahili", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Safaricom PLC",
        role: "Senior Full-Stack Engineer",
        startDate: "2022-01",
        endDate: "Present",
        description: "Built and maintained M-PESA developer portal used by 3,000+ API integrators. Led migration from Angular to Next.js, reducing load times by 40%.",
        technologies: ["Next.js", "Node.js", "TypeScript", "PostgreSQL", "Redis"],
        isCurrent: true,
      },
      {
        company: "Chumz",
        role: "Frontend Engineer",
        startDate: "2019-08",
        endDate: "2021-12",
        description: "Built React Native and web interfaces for a savings app with 80,000 active users.",
        technologies: ["React", "React Native", "Redux", "Node.js"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "University of Nairobi",
        degree: "Bachelor's",
        fieldOfStudy: "Computer Science",
        startYear: 2015,
        endYear: 2019,
      },
    ],
    certifications: [
      { name: "Meta React Developer", issuer: "Meta / Coursera", issueDate: "2022-08" },
    ],
    projects: [
      {
        name: "DevHub Kenya",
        description: "Community platform for Kenyan developers with job boards, events, and resources.",
        technologies: ["Next.js", "Node.js", "MongoDB", "Tailwind CSS"],
        role: "Co-Founder & Lead Engineer",
        link: "https://devhub.co.ke",
        startDate: "2022-06",
        endDate: "2023-12",
      },
    ],
    availability: { status: "Open to Opportunities", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/brian-odhiambo",
      github: "https://github.com/brianodh",
    },
    source: "platform",
  },
  {
    firstName: "Claire",
    lastName: "Uwimana",
    email: "claire.uwimana@example.com",
    headline: "AI/ML Engineer – LLM Systems & Python | 4 Years",
    bio: "AI engineer focused on building production-grade LLM applications and recommendation systems. Google Developer Expert in ML.",
    location: "Kigali, Rwanda",
    skills: [
      { name: "Python", level: "Expert", yearsOfExperience: 6 },
      { name: "TensorFlow", level: "Advanced", yearsOfExperience: 4 },
      { name: "Gemini API", level: "Expert", yearsOfExperience: 2 },
      { name: "FastAPI", level: "Advanced", yearsOfExperience: 3 },
      { name: "LangChain", level: "Advanced", yearsOfExperience: 2 },
      { name: "Node.js", level: "Intermediate", yearsOfExperience: 2 },
      { name: "MongoDB", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Docker", level: "Intermediate", yearsOfExperience: 3 },
    ],
    languages: [
      { name: "English", proficiency: "Fluent" },
      { name: "Kinyarwanda", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Google",
        role: "AI Software Engineer (Contract)",
        startDate: "2023-01",
        endDate: "Present",
        description: "Worked on Gemini API developer experience team. Built reference implementations and prompt engineering guides. Reduced average prompt token usage by 35% through optimization.",
        technologies: ["Python", "Gemini API", "LangChain", "FastAPI"],
        isCurrent: true,
      },
      {
        company: "InstaDeep",
        role: "Machine Learning Engineer",
        startDate: "2020-09",
        endDate: "2022-12",
        description: "Built reinforcement learning models for logistics optimization across 4 African countries.",
        technologies: ["Python", "TensorFlow", "PyTorch", "Kubernetes"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "African Institute for Mathematical Sciences",
        degree: "Master's",
        fieldOfStudy: "Machine Intelligence",
        startYear: 2018,
        endYear: 2020,
      },
    ],
    certifications: [
      { name: "Google Professional ML Engineer", issuer: "Google", issueDate: "2022-04" },
      { name: "Deep Learning Specialization", issuer: "DeepLearning.AI", issueDate: "2021-01" },
    ],
    projects: [
      {
        name: "RecruitAI",
        description: "AI screening system using Gemini to rank candidates with 85% recruiter satisfaction rate.",
        technologies: ["Python", "Gemini API", "FastAPI", "MongoDB"],
        role: "Lead AI Engineer",
        startDate: "2023-08",
        endDate: "2024-01",
      },
    ],
    availability: { status: "Available", type: "Contract" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/claire-uwimana",
      github: "https://github.com/claireuw",
      portfolio: "https://claireuwimana.dev",
    },
    source: "platform",
  },
  {
    firstName: "David",
    lastName: "Mensah",
    email: "david.mensah@example.com",
    headline: "DevOps & Cloud Engineer – AWS & Kubernetes | 6 Years",
    bio: "Cloud infrastructure specialist with deep expertise in AWS, Kubernetes, and CI/CD pipelines. Built infrastructure for platforms scaling to millions of users.",
    location: "Accra, Ghana",
    skills: [
      { name: "AWS", level: "Expert", yearsOfExperience: 6 },
      { name: "Kubernetes", level: "Advanced", yearsOfExperience: 4 },
      { name: "Docker", level: "Expert", yearsOfExperience: 5 },
      { name: "Terraform", level: "Advanced", yearsOfExperience: 4 },
      { name: "Node.js", level: "Intermediate", yearsOfExperience: 3 },
      { name: "GitHub Actions", level: "Advanced", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Python", level: "Intermediate", yearsOfExperience: 3 },
    ],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Twi", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Flutterwave",
        role: "Senior DevOps Engineer",
        startDate: "2020-04",
        endDate: "Present",
        description: "Managed cloud infrastructure processing $10B+ annual transactions. Reduced deployment time from 45 minutes to 8 minutes via optimized CI/CD. Zero downtime deployments.",
        technologies: ["AWS", "Kubernetes", "Terraform", "GitHub Actions", "Prometheus"],
        isCurrent: true,
      },
      {
        company: "Jumia",
        role: "Cloud Infrastructure Engineer",
        startDate: "2018-01",
        endDate: "2020-03",
        description: "Migrated monolith to microservices on AWS EKS. Managed 200+ services across 3 regions.",
        technologies: ["AWS", "Docker", "Jenkins", "Ansible"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "Kwame Nkrumah University of Science and Technology",
        degree: "Bachelor's",
        fieldOfStudy: "Computer Engineering",
        startYear: 2013,
        endYear: 2017,
      },
    ],
    certifications: [
      { name: "AWS Certified DevOps Engineer Professional", issuer: "Amazon", issueDate: "2021-06" },
      { name: "Certified Kubernetes Administrator (CKA)", issuer: "CNCF", issueDate: "2022-01" },
    ],
    projects: [
      {
        name: "AfriCloud",
        description: "Open-source toolkit for deploying African fintech apps on AWS with compliance templates.",
        technologies: ["Terraform", "AWS", "Python", "Docker"],
        role: "Creator",
        link: "https://github.com/dmensah/africloud",
        startDate: "2021-03",
        endDate: "2022-06",
      },
    ],
    availability: { status: "Open to Opportunities", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/david-mensah-devops",
      github: "https://github.com/dmensah",
    },
    source: "platform",
  },
  {
    firstName: "Fatima",
    lastName: "Al-Hassan",
    email: "fatima.alhassan@example.com",
    headline: "Product Engineer – React Native & TypeScript | 4 Years",
    bio: "Mobile-first product engineer building cross-platform apps. Led product development for fintech apps used across West Africa.",
    location: "Lagos, Nigeria",
    skills: [
      { name: "React Native", level: "Expert", yearsOfExperience: 4 },
      { name: "TypeScript", level: "Advanced", yearsOfExperience: 4 },
      { name: "React", level: "Advanced", yearsOfExperience: 4 },
      { name: "Node.js", level: "Intermediate", yearsOfExperience: 3 },
      { name: "Firebase", level: "Advanced", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Redux", level: "Advanced", yearsOfExperience: 3 },
    ],
    languages: [
      { name: "English", proficiency: "Fluent" },
      { name: "Hausa", proficiency: "Native" },
      { name: "Yoruba", proficiency: "Conversational" },
    ],
    experience: [
      {
        company: "PiggyVest",
        role: "Senior Product Engineer",
        startDate: "2021-07",
        endDate: "Present",
        description: "Led React Native development for savings app with 4.8/5 App Store rating and 500,000+ downloads. Built real-time notifications reducing user churn by 22%.",
        technologies: ["React Native", "TypeScript", "Redux", "Firebase", "Node.js"],
        isCurrent: true,
      },
      {
        company: "Patricia",
        role: "Mobile Engineer",
        startDate: "2019-02",
        endDate: "2021-06",
        description: "Built crypto trading mobile app features. Implemented biometric authentication and real-time price charts.",
        technologies: ["React Native", "JavaScript", "Firebase"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "University of Lagos",
        degree: "Bachelor's",
        fieldOfStudy: "Software Engineering",
        startYear: 2015,
        endYear: 2019,
      },
    ],
    certifications: [
      { name: "React Native Specialist", issuer: "Udemy", issueDate: "2020-03" },
    ],
    projects: [
      {
        name: "Susu",
        description: "Group savings app inspired by traditional West African susu, with AI-powered savings goals.",
        technologies: ["React Native", "Node.js", "Firebase", "TypeScript"],
        role: "Lead Developer",
        link: "https://susuapp.ng",
        startDate: "2022-01",
        endDate: "2023-06",
      },
    ],
    availability: { status: "Available", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/fatima-alhassan",
      github: "https://github.com/fatimaalh",
    },
    source: "platform",
  },
  {
    firstName: "Georges",
    lastName: "Ndayishimiye",
    email: "georges.nday@example.com",
    headline: "Backend Engineer – Java Spring & Microservices | 5 Years",
    bio: "Java/Spring Boot specialist building enterprise microservices for banking and insurance sectors in East Africa.",
    location: "Bujumbura, Burundi",
    skills: [
      { name: "Java", level: "Expert", yearsOfExperience: 5 },
      { name: "Spring Boot", level: "Expert", yearsOfExperience: 5 },
      { name: "PostgreSQL", level: "Advanced", yearsOfExperience: 4 },
      { name: "Node.js", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Docker", level: "Advanced", yearsOfExperience: 3 },
      { name: "RabbitMQ", level: "Advanced", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Beginner", yearsOfExperience: 1 },
    ],
    languages: [
      { name: "French", proficiency: "Native" },
      { name: "English", proficiency: "Fluent" },
      { name: "Kirundi", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Ecobank",
        role: "Backend Engineer",
        startDate: "2021-03",
        endDate: "Present",
        description: "Built core banking microservices for loan origination, KYC, and account management. Services handle 200,000+ transactions daily.",
        technologies: ["Java", "Spring Boot", "PostgreSQL", "RabbitMQ", "Docker"],
        isCurrent: true,
      },
      {
        company: "SORAS Group",
        role: "Java Developer",
        startDate: "2018-09",
        endDate: "2021-02",
        description: "Developed insurance management system for Rwanda's largest insurer.",
        technologies: ["Java", "Spring", "Oracle DB"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "Université du Burundi",
        degree: "Bachelor's",
        fieldOfStudy: "Computer Science",
        startYear: 2013,
        endYear: 2017,
      },
    ],
    certifications: [
      { name: "Oracle Certified Java Professional", issuer: "Oracle", issueDate: "2020-07" },
    ],
    projects: [
      {
        name: "LoanFlow",
        description: "Automated loan processing system reducing approval time from 5 days to 4 hours.",
        technologies: ["Java", "Spring Boot", "PostgreSQL", "React"],
        role: "Backend Lead",
        startDate: "2021-06",
        endDate: "2022-03",
      },
    ],
    availability: { status: "Open to Opportunities", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/georges-nday",
    },
    source: "platform",
  },
  {
    firstName: "Helen",
    lastName: "Amoah",
    email: "helen.amoah@example.com",
    headline: "Data Engineer – Python, Spark & ETL Pipelines | 4 Years",
    bio: "Data engineer specializing in building scalable data pipelines and warehouses. Passionate about using data to drive product decisions in African tech.",
    location: "Accra, Ghana",
    skills: [
      { name: "Python", level: "Expert", yearsOfExperience: 5 },
      { name: "Apache Spark", level: "Advanced", yearsOfExperience: 3 },
      { name: "dbt", level: "Advanced", yearsOfExperience: 2 },
      { name: "PostgreSQL", level: "Advanced", yearsOfExperience: 4 },
      { name: "MongoDB", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Airflow", level: "Advanced", yearsOfExperience: 3 },
      { name: "Node.js", level: "Beginner", yearsOfExperience: 1 },
      { name: "BigQuery", level: "Advanced", yearsOfExperience: 2 },
    ],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Twi", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Chipper Cash",
        role: "Senior Data Engineer",
        startDate: "2022-04",
        endDate: "Present",
        description: "Built real-time fraud detection pipelines processing 5M+ daily transactions. Reduced data pipeline latency from 4 hours to 15 minutes.",
        technologies: ["Python", "Apache Spark", "Airflow", "BigQuery", "dbt"],
        isCurrent: true,
      },
      {
        company: "mPharma",
        role: "Data Engineer",
        startDate: "2019-06",
        endDate: "2022-03",
        description: "Built inventory forecasting models and supply chain ETL pipelines for 400+ pharmacies.",
        technologies: ["Python", "PostgreSQL", "Airflow", "AWS S3"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "University of Ghana",
        degree: "Bachelor's",
        fieldOfStudy: "Statistics",
        startYear: 2015,
        endYear: 2019,
      },
    ],
    certifications: [
      { name: "Google Professional Data Engineer", issuer: "Google", issueDate: "2023-03" },
      { name: "dbt Certified Developer", issuer: "dbt Labs", issueDate: "2022-09" },
    ],
    projects: [
      {
        name: "AfriMetrics",
        description: "Open-source dashboard aggregating economic and tech metrics across 54 African countries.",
        technologies: ["Python", "BigQuery", "Airflow", "Next.js"],
        role: "Data Lead",
        link: "https://afrimetrics.io",
        startDate: "2023-01",
        endDate: "2023-12",
      },
    ],
    availability: { status: "Available", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/helen-amoah-data",
      github: "https://github.com/helenamoah",
    },
    source: "platform",
  },
  {
    firstName: "Ibrahim",
    lastName: "Diallo",
    email: "ibrahim.diallo@example.com",
    headline: "Junior Full-Stack Developer – React & Node.js | 1.5 Years",
    bio: "Motivated junior developer eager to grow in a fast-paced team. Built several personal projects and completed Andela technical training.",
    location: "Dakar, Senegal",
    skills: [
      { name: "React", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Node.js", level: "Intermediate", yearsOfExperience: 1 },
      { name: "JavaScript", level: "Intermediate", yearsOfExperience: 2 },
      { name: "MongoDB", level: "Beginner", yearsOfExperience: 1 },
      { name: "CSS/Tailwind", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Git", level: "Intermediate", yearsOfExperience: 2 },
    ],
    languages: [
      { name: "French", proficiency: "Native" },
      { name: "English", proficiency: "Conversational" },
      { name: "Wolof", proficiency: "Native" },
    ],
    experience: [
      {
        company: "OuiBuild",
        role: "Junior Frontend Developer",
        startDate: "2024-07",
        endDate: "Present",
        description: "Building React components for a construction project management platform. Implemented responsive design and API integrations.",
        technologies: ["React", "Tailwind CSS", "REST APIs"],
        isCurrent: true,
      },
    ],
    education: [
      {
        institution: "École Supérieure Polytechnique de Dakar",
        degree: "Bachelor's",
        fieldOfStudy: "Software Engineering",
        startYear: 2019,
        endYear: 2023,
      },
    ],
    certifications: [
      { name: "Andela Technical Leadership Program", issuer: "Andela", issueDate: "2024-03" },
    ],
    projects: [
      {
        name: "JobBoard Sénégal",
        description: "French-language job board for Senegalese tech professionals.",
        technologies: ["React", "Node.js", "MongoDB"],
        role: "Full-Stack Developer",
        startDate: "2023-08",
        endDate: "2024-02",
      },
    ],
    availability: { status: "Available", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/ibrahim-diallo-dev",
      github: "https://github.com/ibrahimdiallo",
    },
    source: "platform",
  },
  {
    firstName: "Joyce",
    lastName: "Mutua",
    email: "joyce.mutua@example.com",
    headline: "UX Engineer – React & Design Systems | 3 Years",
    bio: "UX Engineer bridging design and engineering. Built design systems used across multiple product teams. Figma expert and accessibility advocate.",
    location: "Nairobi, Kenya",
    skills: [
      { name: "React", level: "Advanced", yearsOfExperience: 3 },
      { name: "TypeScript", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Tailwind CSS", level: "Expert", yearsOfExperience: 3 },
      { name: "Figma", level: "Expert", yearsOfExperience: 4 },
      { name: "Storybook", level: "Advanced", yearsOfExperience: 2 },
      { name: "Next.js", level: "Intermediate", yearsOfExperience: 2 },
      { name: "CSS/SASS", level: "Expert", yearsOfExperience: 4 },
    ],
    languages: [
      { name: "English", proficiency: "Fluent" },
      { name: "Swahili", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Coda",
        role: "UX Engineer",
        startDate: "2022-09",
        endDate: "Present",
        description: "Built and maintained Coda's design system used by 12 product teams. Created 80+ accessible React components. Reduced design-to-code time by 60%.",
        technologies: ["React", "TypeScript", "Storybook", "Tailwind CSS", "Figma"],
        isCurrent: true,
      },
      {
        company: "Twiga Foods",
        role: "Frontend Developer",
        startDate: "2020-11",
        endDate: "2022-08",
        description: "Built merchant dashboard for Africa's largest B2B food platform.",
        technologies: ["React", "JavaScript", "Material UI"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "Strathmore University",
        degree: "Bachelor's",
        fieldOfStudy: "Informatics",
        startYear: 2016,
        endYear: 2020,
      },
    ],
    certifications: [
      { name: "Google UX Design Certificate", issuer: "Google / Coursera", issueDate: "2021-05" },
    ],
    projects: [
      {
        name: "AccessKit",
        description: "Open-source accessible component library for African-market apps with RTL and multilingual support.",
        technologies: ["React", "TypeScript", "Storybook", "Radix UI"],
        role: "Creator & Maintainer",
        link: "https://github.com/jmutua/accesskit",
        startDate: "2023-03",
        endDate: "2024-01",
      },
    ],
    availability: { status: "Open to Opportunities", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/joyce-mutua-ux",
      github: "https://github.com/jmutua",
      portfolio: "https://joycemutua.design",
    },
    source: "platform",
  },
  {
    firstName: "Kevin",
    lastName: "Osei",
    email: "kevin.osei@example.com",
    headline: "Backend Engineer – Python & FastAPI | 3 Years",
    bio: "Python backend engineer with expertise in FastAPI, async programming, and ML model serving. Building Africa's AI infrastructure.",
    location: "Kumasi, Ghana",
    skills: [
      { name: "Python", level: "Advanced", yearsOfExperience: 4 },
      { name: "FastAPI", level: "Advanced", yearsOfExperience: 3 },
      { name: "PostgreSQL", level: "Intermediate", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Docker", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Celery", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Node.js", level: "Beginner", yearsOfExperience: 1 },
      { name: "TypeScript", level: "Beginner", yearsOfExperience: 1 },
    ],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Twi", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Hubtel",
        role: "Backend Engineer",
        startDate: "2022-05",
        endDate: "Present",
        description: "Built FastAPI microservices for Ghana's largest digital commerce platform. Implemented async order processing handling 10,000 orders/hour.",
        technologies: ["Python", "FastAPI", "PostgreSQL", "Celery", "Redis"],
        isCurrent: true,
      },
      {
        company: "Farmerline",
        role: "Python Developer",
        startDate: "2020-02",
        endDate: "2022-04",
        description: "Built SMS-based advisory APIs for smallholder farmers. Created ML crop disease prediction model.",
        technologies: ["Python", "Flask", "PostgreSQL", "Scikit-learn"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "Kwame Nkrumah University of Science and Technology",
        degree: "Bachelor's",
        fieldOfStudy: "Computer Science",
        startYear: 2016,
        endYear: 2020,
      },
    ],
    certifications: [
      { name: "FastAPI Expert Track", issuer: "TestDriven.io", issueDate: "2022-11" },
    ],
    projects: [
      {
        name: "CropAI",
        description: "AI-powered crop disease detection API serving 5,000 farmers across Ghana.",
        technologies: ["Python", "FastAPI", "TensorFlow", "MongoDB"],
        role: "Lead Developer",
        startDate: "2021-04",
        endDate: "2022-01",
      },
    ],
    availability: { status: "Available", type: "Contract" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/kevin-osei-py",
      github: "https://github.com/kevinosei",
    },
    source: "platform",
  },
  {
    firstName: "Laila",
    lastName: "Benali",
    email: "laila.benali@example.com",
    headline: "Senior Frontend Engineer – Vue.js & TypeScript | 5 Years",
    bio: "Vue.js specialist with 5 years building enterprise dashboards and design-forward interfaces for North African markets.",
    location: "Casablanca, Morocco",
    skills: [
      { name: "Vue.js", level: "Expert", yearsOfExperience: 5 },
      { name: "TypeScript", level: "Advanced", yearsOfExperience: 4 },
      { name: "React", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Node.js", level: "Intermediate", yearsOfExperience: 3 },
      { name: "GraphQL", level: "Advanced", yearsOfExperience: 3 },
      { name: "Tailwind CSS", level: "Advanced", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Beginner", yearsOfExperience: 1 },
    ],
    languages: [
      { name: "Arabic", proficiency: "Native" },
      { name: "French", proficiency: "Fluent" },
      { name: "English", proficiency: "Fluent" },
    ],
    experience: [
      {
        company: "Moroccan Digital Agency",
        role: "Senior Frontend Engineer",
        startDate: "2021-02",
        endDate: "Present",
        description: "Led frontend for Morocco's national digital ID portal used by 2M+ citizens. Implemented accessibility standards and Arabic RTL support.",
        technologies: ["Vue.js", "TypeScript", "GraphQL", "Tailwind CSS"],
        isCurrent: true,
      },
    ],
    education: [
      {
        institution: "École Mohammadia d'Ingénieurs",
        degree: "Master's",
        fieldOfStudy: "Software Engineering",
        startYear: 2016,
        endYear: 2021,
      },
    ],
    certifications: [],
    projects: [
      {
        name: "RTL Component Library",
        description: "Open-source Vue.js component library with built-in Arabic/RTL support.",
        technologies: ["Vue.js", "TypeScript", "CSS"],
        role: "Creator",
        startDate: "2022-06",
        endDate: "2023-06",
      },
    ],
    availability: { status: "Open to Opportunities", type: "Full-time" },
    socialLinks: { linkedin: "https://linkedin.com/in/laila-benali-vue" },
    source: "platform",
  },
  {
    firstName: "Michael",
    lastName: "Agyemang",
    email: "michael.agyemang@example.com",
    headline: "Tech Lead – Node.js & System Architecture | 8 Years",
    bio: "Experienced tech lead and systems architect. Led teams of 8-15 engineers building financial infrastructure. Strong technical mentor.",
    location: "Accra, Ghana",
    skills: [
      { name: "Node.js", level: "Expert", yearsOfExperience: 8 },
      { name: "TypeScript", level: "Expert", yearsOfExperience: 6 },
      { name: "MongoDB", level: "Expert", yearsOfExperience: 7 },
      { name: "PostgreSQL", level: "Expert", yearsOfExperience: 6 },
      { name: "System Design", level: "Expert", yearsOfExperience: 8 },
      { name: "React", level: "Advanced", yearsOfExperience: 5 },
      { name: "AWS", level: "Advanced", yearsOfExperience: 5 },
      { name: "Kubernetes", level: "Intermediate", yearsOfExperience: 3 },
    ],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Twi", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Paystack",
        role: "Tech Lead",
        startDate: "2019-01",
        endDate: "Present",
        description: "Led team of 12 engineers building Paystack's core payments infrastructure. Architected event-driven system handling $100M+ monthly volume. Mentored 6 junior engineers to mid-level.",
        technologies: ["Node.js", "TypeScript", "PostgreSQL", "MongoDB", "Kafka", "AWS"],
        isCurrent: true,
      },
      {
        company: "Sendy",
        role: "Senior Backend Engineer",
        startDate: "2016-05",
        endDate: "2018-12",
        description: "Built logistics matching algorithm serving 5,000 daily deliveries across East Africa.",
        technologies: ["Node.js", "MongoDB", "Redis", "Google Maps API"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "University of Ghana",
        degree: "Bachelor's",
        fieldOfStudy: "Computer Science",
        startYear: 2010,
        endYear: 2014,
      },
    ],
    certifications: [
      { name: "AWS Solutions Architect Professional", issuer: "Amazon", issueDate: "2020-09" },
    ],
    projects: [
      {
        name: "Payments Orchestration Engine",
        description: "Open-source payment routing engine supporting 12 African payment providers.",
        technologies: ["Node.js", "TypeScript", "PostgreSQL", "Redis"],
        role: "Architect & Lead",
        link: "https://github.com/magyemang/poe",
        startDate: "2022-01",
        endDate: "2023-12",
      },
    ],
    availability: { status: "Open to Opportunities", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/michael-agyemang-tech",
      github: "https://github.com/magyemang",
    },
    source: "platform",
  },
  {
    firstName: "Nadia",
    lastName: "Traore",
    email: "nadia.traore@example.com",
    headline: "Security Engineer – Node.js & API Security | 4 Years",
    bio: "Application security engineer specializing in securing Node.js APIs and implementing zero-trust architectures.",
    location: "Abidjan, Côte d'Ivoire",
    skills: [
      { name: "Node.js", level: "Advanced", yearsOfExperience: 4 },
      { name: "TypeScript", level: "Advanced", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Intermediate", yearsOfExperience: 3 },
      { name: "OAuth2/JWT", level: "Expert", yearsOfExperience: 4 },
      { name: "Penetration Testing", level: "Advanced", yearsOfExperience: 3 },
      { name: "Docker", level: "Intermediate", yearsOfExperience: 3 },
      { name: "Python", level: "Intermediate", yearsOfExperience: 3 },
    ],
    languages: [
      { name: "French", proficiency: "Native" },
      { name: "English", proficiency: "Fluent" },
      { name: "Dioula", proficiency: "Native" },
    ],
    experience: [
      {
        company: "Orange Digital Center",
        role: "Application Security Engineer",
        startDate: "2021-09",
        endDate: "Present",
        description: "Secured APIs for Orange Money serving 12 million users across West Africa. Conducted 40+ penetration tests. Reduced critical vulnerabilities by 78%.",
        technologies: ["Node.js", "TypeScript", "OAuth2", "Docker", "OWASP"],
        isCurrent: true,
      },
    ],
    education: [
      {
        institution: "Institut National Polytechnique Félix Houphouët-Boigny",
        degree: "Master's",
        fieldOfStudy: "Cybersecurity",
        startYear: 2016,
        endYear: 2021,
      },
    ],
    certifications: [
      { name: "Certified Ethical Hacker (CEH)", issuer: "EC-Council", issueDate: "2022-06" },
      { name: "CompTIA Security+", issuer: "CompTIA", issueDate: "2021-11" },
    ],
    projects: [
      {
        name: "APIShield",
        description: "Middleware library for Node.js APIs providing automatic OWASP Top 10 protection.",
        technologies: ["Node.js", "TypeScript"],
        role: "Creator",
        link: "https://github.com/ntraore/apishield",
        startDate: "2022-08",
        endDate: "2023-04",
      },
    ],
    availability: { status: "Available", type: "Contract" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/nadia-traore-sec",
      github: "https://github.com/ntraore",
    },
    source: "platform",
  },
  {
    firstName: "Omar",
    lastName: "Farouk",
    email: "omar.farouk@example.com",
    headline: "Full-Stack Engineer – Next.js & MongoDB | 3 Years",
    bio: "Full-stack engineer with a strong product sense. Builds end-to-end features from database design to pixel-perfect UIs.",
    location: "Cairo, Egypt",
    skills: [
      { name: "Next.js", level: "Advanced", yearsOfExperience: 3 },
      { name: "TypeScript", level: "Advanced", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Advanced", yearsOfExperience: 3 },
      { name: "Node.js", level: "Advanced", yearsOfExperience: 3 },
      { name: "Tailwind CSS", level: "Advanced", yearsOfExperience: 2 },
      { name: "Redux", level: "Intermediate", yearsOfExperience: 2 },
      { name: "GraphQL", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Gemini API", level: "Intermediate", yearsOfExperience: 1 },
    ],
    languages: [
      { name: "Arabic", proficiency: "Native" },
      { name: "English", proficiency: "Fluent" },
    ],
    experience: [
      {
        company: "Instabug",
        role: "Full-Stack Engineer",
        startDate: "2022-03",
        endDate: "Present",
        description: "Built customer-facing dashboard and internal tooling. Led integration of AI bug classification feature reducing triage time by 35%.",
        technologies: ["Next.js", "TypeScript", "MongoDB", "Node.js", "Gemini API"],
        isCurrent: true,
      },
      {
        company: "El Menus",
        role: "Frontend Developer",
        startDate: "2020-06",
        endDate: "2022-02",
        description: "Built React-based restaurant management SaaS used by 400+ restaurants.",
        technologies: ["React", "JavaScript", "Node.js", "MongoDB"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "Cairo University",
        degree: "Bachelor's",
        fieldOfStudy: "Computer Science",
        startYear: 2016,
        endYear: 2020,
      },
    ],
    certifications: [],
    projects: [
      {
        name: "HireAI",
        description: "AI job matching platform for Arab tech professionals using Gemini API for semantic matching.",
        technologies: ["Next.js", "Node.js", "MongoDB", "Gemini API", "Tailwind CSS"],
        role: "Solo Developer",
        startDate: "2024-01",
        endDate: "2024-06",
      },
    ],
    availability: { status: "Available", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/omar-farouk-dev",
      github: "https://github.com/ofarouk",
    },
    source: "platform",
  },
  {
    firstName: "Priya",
    lastName: "Naidoo",
    email: "priya.naidoo@example.com",
    headline: "Backend Engineer – Node.js & Microservices | 4 Years",
    bio: "Backend engineer with fintech and healthtech background. Builds robust, well-tested APIs with a focus on reliability and developer experience.",
    location: "Johannesburg, South Africa",
    skills: [
      { name: "Node.js", level: "Advanced", yearsOfExperience: 4 },
      { name: "TypeScript", level: "Advanced", yearsOfExperience: 3 },
      { name: "MongoDB", level: "Advanced", yearsOfExperience: 4 },
      { name: "PostgreSQL", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Jest", level: "Advanced", yearsOfExperience: 3 },
      { name: "Docker", level: "Intermediate", yearsOfExperience: 2 },
      { name: "Gemini API", level: "Beginner", yearsOfExperience: 1 },
      { name: "AWS", level: "Intermediate", yearsOfExperience: 2 },
    ],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Zulu", proficiency: "Conversational" },
    ],
    experience: [
      {
        company: "Discovery Health",
        role: "Backend Engineer",
        startDate: "2021-06",
        endDate: "Present",
        description: "Built health data APIs serving 8M+ medical aid members. Implemented FHIR-compliant data exchange and POPIA-compliant data handling.",
        technologies: ["Node.js", "TypeScript", "MongoDB", "PostgreSQL", "AWS", "Jest"],
        isCurrent: true,
      },
      {
        company: "OfferZen",
        role: "Junior Backend Developer",
        startDate: "2019-08",
        endDate: "2021-05",
        description: "Built APIs for a developer talent marketplace connecting 30,000+ SA developers with employers.",
        technologies: ["Node.js", "MongoDB", "JavaScript"],
        isCurrent: false,
      },
    ],
    education: [
      {
        institution: "University of Cape Town",
        degree: "Bachelor's",
        fieldOfStudy: "Information Systems",
        startYear: 2015,
        endYear: 2019,
      },
    ],
    certifications: [
      { name: "AWS Certified Developer Associate", issuer: "Amazon", issueDate: "2022-08" },
    ],
    projects: [
      {
        name: "MedSync",
        description: "FHIR-compliant patient record sync API used by 50+ South African clinics.",
        technologies: ["Node.js", "TypeScript", "MongoDB", "FHIR"],
        role: "Lead Developer",
        startDate: "2022-03",
        endDate: "2023-01",
      },
    ],
    availability: { status: "Available", type: "Full-time" },
    socialLinks: {
      linkedin: "https://linkedin.com/in/priya-naidoo-dev",
      github: "https://github.com/priyanaidoo",
    },
    source: "platform",
  },
];
